name: Docker (proxy)

on:
  push:
    branches: ["main"]
    paths:
      - proxy/**
  pull_request:
    branches: ["main"]
    paths:
      - proxy/**

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: proxy/
    steps:
      - uses: actions/checkout@v4
      - run: ./test.sh
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/base.yml
    with:
      service: proxy
      context: proxy/
